### ISSUE TITLE
Failed test: fieldPikaday.vue check template: model value should be the input value if changed

### ISSUE THREAD

**Issue by dflock** [icebob/vue-form-generator#203]
This is on current master, running `npm run test`:

```
fieldPikaday.vue
    check template
      ✓ should contain an input text element
      ✓ should contain the value
      ✓ input value should be the model value after changed
      ✗ model value should be the input value if changed
	AssertionError: expected '2014-12-30' to equal '2014-12-31' (undefined:111)
```

**Comment by icebob** [comment]
I tested and it seems everything is OK
```
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 410 of 424 (skipped 14) SUCCESS (2.615 secs / 1.251 secs)
TOTAL: 410 SUCCESS


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

**Comment by dflock** [comment]
Hmmm. Doesn't work for me:

```console
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
...
```
```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 416 of 430 (1 FAILED) (skipped 14) (2.085 secs / NaN secs)
TOTAL: 1 FAILED, 415 SUCCESS


1) model value should be the input value if changed
     fieldPikaday.vue check template
     AssertionError: expected '2014-12-30' to equal '2014-12-31' (undefined:111)



=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

Here's the contents of the `npm-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle vue-form-generator@2.0.0-beta6~pretest: vue-form-generator@2.0.0-beta6
6 verbose lifecycle vue-form-generator@2.0.0-beta6~pretest: unsafe-perm in lifecycle true
7 verbose lifecycle vue-form-generator@2.0.0-beta6~pretest: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/duncan/dev/vue-form-generator/node_modules/.bin:/home/duncan/.cabal/bin:./node_modules/.bin:/home/duncan/.yarn-config/global/bin:~/.npm-packages/bin:/home/duncan/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/var/data/phemi/utils
8 verbose lifecycle vue-form-generator@2.0.0-beta6~pretest: CWD: /home/duncan/dev/vue-form-generator
9 silly lifecycle vue-form-generator@2.0.0-beta6~pretest: Args: [ '-c', 'npm run lint' ]
10 silly lifecycle vue-form-generator@2.0.0-beta6~pretest: Returned: code: 0  signal: null
11 info lifecycle vue-form-generator@2.0.0-beta6~test: vue-form-generator@2.0.0-beta6
12 verbose lifecycle vue-form-generator@2.0.0-beta6~test: unsafe-perm in lifecycle true
13 verbose lifecycle vue-form-generator@2.0.0-beta6~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/duncan/dev/vue-form-generator/node_modules/.bin:/home/duncan/.cabal/bin:./node_modules/.bin:/home/duncan/.yarn-config/global/bin:~/.npm-packages/bin:/home/duncan/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/var/data/phemi/utils
14 verbose lifecycle vue-form-generator@2.0.0-beta6~test: CWD: /home/duncan/dev/vue-form-generator
15 silly lifecycle vue-form-generator@2.0.0-beta6~test: Args: [ '-c', 'npm run unit' ]
16 silly lifecycle vue-form-generator@2.0.0-beta6~test: Returned: code: 1  signal: null
17 info lifecycle vue-form-generator@2.0.0-beta6~test: Failed to exec test script
18 verbose stack Error: vue-form-generator@2.0.0-beta6 test: `npm run unit`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:886:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid vue-form-generator@2.0.0-beta6
20 verbose cwd /home/duncan/dev/vue-form-generator
21 error Linux 4.4.0-62-generic
22 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
23 error node v6.10.3
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error vue-form-generator@2.0.0-beta6 test: `npm run unit`
26 error Exit status 1
27 error Failed at the vue-form-generator@2.0.0-beta6 test script 'npm run unit'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the vue-form-generator package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     npm run unit
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs vue-form-generator
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls vue-form-generator
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by glowens** [comment]
I see this is closed but I am having the same problem.
